### ISSUE TITLE
Added to Semantic UI

### ISSUE THREAD

**Issue by jlukic** [bevacqua/fuzzysearch#10]
Just wanted to let you know that I've added your fuzzy search algorithm to our [search component](http://semantic-ui.com/modules/search.html#local-search)

Code can be [seen here](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L464)

**Comment by bevacqua** [comment]
Sweet! Thanks for the heads up. Enjoy
