### ISSUE TITLE
Different from indexOf?

### ISSUE THREAD

**Issue by laander** [bevacqua/fuzzysearch#15]
I might be misunderstanding something here, but how is this different from:  
`haystack.indexOf(needle) >= 0`

Is it faster?

**Comment by bevacqua** [comment]
It finds `foo` in `frodo` because `frodo` contains `f`, `o`, and `o`, somewhere, in that order.

**Comment by laander** [comment]
Ah, ofcourse. When i scanned the examples in `README.md`, I couldn't spot the "fuzzy" part of it - looked like a regular string search to me. You might want to make that a bit clearer 👍 

Thanks
