### ISSUE TITLE
indexOf is just as fast

### ISSUE THREAD

**Issue by idibidiart** [bevacqua/fuzzysearch#21]
I realize the so-called "high resolution" timers in JS are fucked with due to security reasons, but see below:

var timeOrigin = performance.now() ;fuzzysearch("wrt", "wrtten") ; var timeOrigin2 = performance.now()

timeOrigin2 - timeOrigin
0.0050000089686363935

var timeOrigin = performance.now() ;"wrtten".indexOf("wrt") ; var timeOrigin2 = performance.now()

timeOrigin2 - timeOrigin
0.0050000089686363935

**Comment by bevacqua** [comment]
This doesn't have the same functionality as `indexOf`.

**Comment by idibidiart** [comment]
Your readme shows only one use case! That use case is identical to indexOf method of the String class.

I also looked at the code and it doesn’t do much beyond finding if a certain substring is contained in a certain other string. 

What kind of response is that to say that it has different functionality but no such thing is shown in Readme or in your response or the code itself?

**Comment by bevacqua** [comment]
https://jsperf.com/fuzzysearch-regex/14

**Comment by bevacqua** [comment]
linked in the readme
