### ISSUE TITLE
Where can I find the chat with Mr. Aleph? 

### ISSUE THREAD

**Issue by ajitid** [bevacqua/fuzzysearch#26]
Do you mind pointing me to the issue/PR/discussion you had with Mr. Aleph where he suggested his take?

**Comment by kubk** [comment]
https://github.com/mraleph

**Comment by ajitid** [comment]
Oh

**Comment by ajitid** [comment]
I’m looking for the discussion/PR that happened not the person themself

**Comment by kubk** [comment]
Now you can ask him directly. This repo is being unmaintained for years

**Comment by ajitid** [comment]
Repo author is still active here though, I haven't got a response from him yet so your point is valid also. Closing..
