### ISSUE TITLE
levenshtein algorithm

### ISSUE THREAD

**Issue by NoelDavies** [bevacqua/fuzzysearch#5]
What would be cool is to add the levenshtein algorithm to sort these results.

**Comment by bevacqua** [comment]
Please ellaborate, but I'm not sure what results you mean, since `fuzzysearch` just returns a boolean value

**Comment by nescalante** [comment]
+1

**Comment by NoelDavies** [comment]
@bevacqua The levenshtein algorithm calculates the distance between what the phrase I use to search, and each result.  Find a JS implementation here  - https://github.com/gf3/Levenshtein
