### ISSUE TITLE
Circuit breaker improvement

### ISSUE THREAD

**Issue by jayrhynas** [bevacqua/fuzzysearch#8]
You can return a little earlier when there is no match by replacing the [second breaker](https://github.com/bevacqua/fuzzysearch/blob/072dc6eda207c4d618751677ebff93b7cb902610/index.js#L9-11) with:
```javascript
if (qlen === tlen) {
   return query === text;
}
```
Since if the lengths are equal but the query does **not** equal the text, there is no way the query will match the text.

**Comment by bevacqua** [comment]
Nice one. Care to create a pull request?
